# -*- coding: utf-8 -*-
"""TASK-7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1439b3JeGWEP1RO8QfjyVA11TN7yD29i_
"""

import sqlite3
conn = sqlite3.connect("sales_data.db")  # Connects to existing DB or creates one if not found

query = """
SELECT
    product,
    SUM(quantity) AS total_qty,
    SUM(quantity * price) AS revenue
FROM sales
GROUP BY product
"""

import pandas as pd
df = pd.read_sql_query(query, conn)

print("Sales Summary:\n")
print(df)

import matplotlib.pyplot as plt
df.plot(kind='bar', x='product', y='revenue', legend=False, color='teal')
plt.title("Revenue by Product")
plt.xlabel("Product")
plt.ylabel("Revenue")
plt.tight_layout()

plt.savefig("sales_chart.png")
plt.show()
conn.close()